name: errcheck

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        go: ["1.22.x", "1.23.x", "1.24.x"]
    name: go ${{ matrix.go }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}
    - name: Build
      run: go build -v ./...
    - name: Test
      run: go test -v ./...
